#!/usr/bin/env node
/**
 * Regenerates the facts inside README's status block from the real source of truth, so the
 * README cannot quietly drift from the repo. `--check` fails instead of writing, which is
 * what CI runs.
 *
 *   pnpm docs:sync     rewrite the block
 *   pnpm docs:check    fail if the block is stale
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const check = process.argv.includes("--check");

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const state = readFileSync("docs/STATE.md", "utf8");
const adrCount = readdirSync("docs/decisions").filter((f) =>
  /^\d{4}-.*\.md$/.test(f),
).length;

const milestone =
  /\*\*Milestone:\*\*\s*(.+)/.exec(state)?.[1]?.trim() ?? "unknown";
const nextUp =
  /## Next session picks up\s+\n\*\*([^*]+)\*\*/.exec(state)?.[1]?.trim() ??
  "see docs/STATE.md";

const block = `<!-- BEGIN:status (generated by pnpm docs:sync — do not edit by hand) -->
| | |
| --- | --- |
| Version | \`${pkg.version}\` |
| Milestone | ${milestone} |
| Next up | ${nextUp} |
| Decisions recorded | ${adrCount} ADRs |

Live detail lives in [\`docs/STATE.md\`](docs/STATE.md) — it is rewritten at the end of every
work session.
<!-- END:status -->`;

const readme = readFileSync("README.md", "utf8");
const pattern = /<!-- BEGIN:status[\s\S]*?<!-- END:status -->/;

if (!pattern.test(readme)) {
  console.error(
    "README.md has no <!-- BEGIN:status --> ... <!-- END:status --> block.",
  );
  process.exit(1);
}

const updated = readme.replace(pattern, block);

if (check) {
  if (updated !== readme) {
    console.error(
      "README status block is stale. Run `pnpm docs:sync` and commit the result.",
    );
    process.exit(1);
  }
  console.log("README status block is current");
} else {
  writeFileSync("README.md", updated);
  console.log("README status block updated");
}
